name: JSDocs Automation

on:
  push:
    branches: [main,dev,jsdoc]
jobs:
  jsdocs:
    name: Generate JSDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source/assets/scripts/
          recurse: true
          output_dir: ./out