name: Run Unit Tests

on:
  push:
    branches: [main, dev, game-tests]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test
